server:
  port: 9050
  servlet:
    context-path: /admin

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.84.226.185:13306/test?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: mysql
    password: mysql123

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

